출처 : https://www.kaggle.com/competitions/reducing-commercial-aviation-fatalities

In [2]:
import csv
import pandas as pd
import numpy as np

df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/train.csv')

In [3]:
from sklearn.model_selection import train_test_split

In [4]:
df.head()

,crew,experiment,time,seat,eeg_fp1,eeg_f7,eeg_f8,eeg_t4,eeg_t6,eeg_t5,...,eeg_c4,eeg_p4,eeg_poz,eeg_c3,eeg_cz,eeg_o2,ecg,r,gsr,event
0,1,CA,0.011719,1,-5.28545,26.775801,-9.527310,-12.793200,16.717800,33.737499,...,37.368999,17.437599,19.201900,20.5968,-3.95115,14.507600,-4520.0,817.705994,388.829987,A
1,1,CA,0.015625,1,-2.42842,28.430901,-9.323510,-3.757230,15.969300,30.443600,...,31.170799,19.399700,19.689501,21.3547,1.33212,17.750200,-4520.0,817.705994,388.829987,A
2,1,CA,0.019531,1,10.67150,30.420200,15.350700,24.724001,16.143101,32.142799,...,-12.012600,19.396299,23.171700,22.4076,1.53786,22.247000,-4520.0,817.705994,388.829987,A
3,1,CA,0.023438,1,11.45250,25.609800,2.433080,12.412500,20.533300,31.494101,...,18.574100,23.156401,22.641199,19.3367,2.54492,18.998600,-4520.0,817.705994,388.829987,A
4,1,CA,0.027344,1,7.28321,25.942600,0.113564,5.748000,19.833599,28.753599,...,6.555440,22.754700,22.670300,20.2932,1.69962,22.812799,-4520.0,817.705994,388.829987,A

In [5]:
df_target = df['event']

In [6]:
df_target.head()

0    A
1    A
2    A
3    A
4    A
Name: event, dtype: object

In [10]:
df_input = df.drop("experiment", axis=1)

In [11]:
df_input = df_input.drop("event", axis=1)

In [ ]:
df_input = df_input.drop("crew", axis=1)

In [18]:
train_input, test_input, train_target, test_target = train_test_split(df,df_target,test_size=0.1, shuffle=True, stratify = df_target)

In [19]:
test_input

,crew,experiment,time,seat,eeg_fp1,eeg_f7,eeg_f8,eeg_t4,eeg_t6,eeg_t5,...,eeg_c4,eeg_p4,eeg_poz,eeg_c3,eeg_cz,eeg_o2,ecg,r,gsr,event
300014,1,DA,301.097656,1,163.054001,50.424702,107.766998,25.673901,15.537300,1.64727,...,41.428001,22.360600,22.821899,33.047401,57.251499,12.038700,-2863.770020,816.094971,495.122009,A
672614,2,DA,17.609375,1,13.952000,2.249600,-0.604236,-2.091320,-0.880674,2.85178,...,-2.784100,-0.691598,-7.051430,-1.709500,-2.376380,-2.196850,7743.080078,812.179993,0.000000,A
3517182,7,DA,310.300781,0,-5.671800,-14.266300,5.329680,-3.655650,-4.489290,-1.33197,...,1.181320,-0.607079,-1.302610,-5.347310,-0.789303,0.072962,3702.949951,716.112976,0.000000,D
2777456,6,CA,306.414062,0,2.648260,4.341930,18.224501,3.119870,-0.840124,3.57944,...,4.228360,8.895940,9.427580,5.963670,11.183100,4.932980,31337.000000,656.383972,1157.310059,C
3662972,7,SS,243.204010,0,-22.872999,-3.487660,-15.721500,-9.993100,-4.632820,6.35394,...,0.670512,2.025240,3.124910,10.307100,-4.336870,-0.844808,8069.680176,723.905029,1476.949951,A
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
191359,1,DA,11.882812,0,-13.145800,-5.002240,-9.028110,-12.351700,-0.341113,-1.61849,...,-5.244110,3.692680,3.346590,-3.149700,-0.477884,2.712820,0.000000,659.427979,651.177002,A
429993,1,SS,68.507812,1,0.373711,16.456699,10.434100,3.027300,1.505490,1.11049,...,1.048750,1.468600,-4.552520,0.198100,-23.021400,-11.815700,-4697.899902,819.817017,503.813995,A
877285,2,SS,205.500000,1,-5.886390,-15.329500,2.112410,-3.783910,4.986260,-4.59154,...,-2.947660,0.000000,-0.168811,-6.969410,-5.989200,1.308080,8665.200195,815.931030,0.000000,A
2108338,5,CA,101.171005,0,-24.320601,-20.610300,-19.888100,-13.076400,6.386570,-11.65840,...,-18.263100,-13.623800,-15.378100,-15.943400,-18.828899,-16.135700,-2401.280029,659.010986,1225.619995,C
1758837,4,DA,135.386719,1,1.677150,0.879939,10.186800,6.001140,3.437910,-8.26947,...,11.180000,1.209230,-2.296600,-0.054943,0.185685,4.334180,5834.859863,827.960022,693.210999,A

In [21]:
test_input.to_csv('data_splited.csv')

In [25]:
from google.colab import files
!ls

data_splited.csv  drive  sample_data

In [26]:
files.download('data_splited.csv')