출처 : https://www.kaggle.com/competitions/reducing-commercial-aviation-fatalities

In [ ]:
import csv
import pandas as pd
import numpy as np

df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/train.csv')

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
df.head()

,crew,experiment,time,seat,eeg_fp1,eeg_f7,eeg_f8,eeg_t4,eeg_t6,eeg_t5,...,eeg_c4,eeg_p4,eeg_poz,eeg_c3,eeg_cz,eeg_o2,ecg,r,gsr,event
0,1,CA,0.011719,1,-5.28545,26.775801,-9.527310,-12.793200,16.717800,33.737499,...,37.368999,17.437599,19.201900,20.5968,-3.95115,14.507600,-4520.0,817.705994,388.829987,A
1,1,CA,0.015625,1,-2.42842,28.430901,-9.323510,-3.757230,15.969300,30.443600,...,31.170799,19.399700,19.689501,21.3547,1.33212,17.750200,-4520.0,817.705994,388.829987,A
2,1,CA,0.019531,1,10.67150,30.420200,15.350700,24.724001,16.143101,32.142799,...,-12.012600,19.396299,23.171700,22.4076,1.53786,22.247000,-4520.0,817.705994,388.829987,A
3,1,CA,0.023438,1,11.45250,25.609800,2.433080,12.412500,20.533300,31.494101,...,18.574100,23.156401,22.641199,19.3367,2.54492,18.998600,-4520.0,817.705994,388.829987,A
4,1,CA,0.027344,1,7.28321,25.942600,0.113564,5.748000,19.833599,28.753599,...,6.555440,22.754700,22.670300,20.2932,1.69962,22.812799,-4520.0,817.705994,388.829987,A

In [ ]:
df_target = df['event']

In [ ]:
df_target.head()

0    A
1    A
2    A
3    A
4    A
Name: event, dtype: object

In [ ]:
train_input, test_input, train_target, test_target = train_test_split(df,df_target,test_size=0.1, shuffle=True, stratify = df_target)

In [ ]:
test_input

,crew,experiment,time,seat,eeg_fp1,eeg_f7,eeg_f8,eeg_t4,eeg_t6,eeg_t5,...,eeg_c4,eeg_p4,eeg_poz,eeg_c3,eeg_cz,eeg_o2,ecg,r,gsr,event
713173,2,DA,240.828125,0,29.125601,31.095800,27.985901,19.667900,20.020201,29.470699,...,27.429800,29.011600,26.911900,27.771099,19.212500,24.138000,-4600.229980,735.710022,1222.890015,A
596885,2,CA,37.639000,0,-8.691490,-10.506000,-1.509290,0.054855,14.236300,9.032460,...,2.883160,8.231310,5.377030,-2.177150,-6.612410,4.818950,-4962.500000,739.132996,1215.729980,C
4594002,13,DA,265.648438,0,3.625300,16.025499,0.092139,0.936769,-2.495360,21.086500,...,2.195450,6.145810,9.137440,9.713850,1.924610,9.892200,-16549.000000,681.978027,383.484009,A
1659445,4,CA,285.311005,1,2.360170,0.000000,10.883400,4.714640,5.323970,-14.960700,...,-5.210620,-7.566830,-6.366910,-1.362880,0.666060,-12.377900,6524.890137,825.067993,522.895020,C
132077,1,CA,330.058594,0,-1.052390,-3.697980,-4.853350,8.966970,-18.806499,-10.529600,...,-0.066181,-11.935500,-9.319810,2.988530,-5.997760,-10.403500,-17372.000000,666.338989,776.974976,C
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
284945,1,DA,275.667969,0,-3.229060,5.214030,-7.681320,-4.824650,3.224720,2.791170,...,-4.716630,2.883930,5.142270,8.856250,0.278872,8.974150,0.000000,662.193970,765.406006,A
2786019,6,CA,321.136719,1,-5.978960,-0.361580,7.667440,10.613000,5.084040,-12.469600,...,-0.849250,-1.790850,-3.185390,-3.269720,3.424650,11.218500,10751.200195,796.091980,1648.650024,C
953804,2,SS,34.930000,0,5.018660,1.113560,1.163460,-11.881100,-7.277160,-3.962130,...,2.662580,2.786580,-7.808460,5.167230,-1.814810,-24.567499,-5509.560059,736.815979,900.739014,A
2811128,6,CA,42.230469,1,-12.228100,-9.361430,-9.422950,-11.646100,-14.663100,14.717400,...,-6.601800,-0.102253,1.095090,-1.247110,-4.064430,-12.316500,10929.099609,794.549011,1605.060059,C
3205027,6,SS,87.441406,0,15.953500,10.659100,3.651320,3.560550,-3.722110,1.865650,...,4.823890,2.410930,0.405698,-1.626810,7.101310,-2.707510,27243.199219,647.921021,866.500000,B

In [ ]:
test_input.to_csv('data_splited2.csv')

In [ ]:
from google.colab import files
!ls

data_splited2.csv  data_splited.csv  drive  sample_data

In [ ]:
files.download('data_splited2.csv')